"""The manipulation search for the couples mechanism (`witness.couples`) --
re-derived independently for this mechanism, not inherited from
`witness.search`, per REVIEWER.md ("Never inherit a theorem across
mechanisms" / "Re-derive, don't inherit, for each new mechanism").

WHY THIS IS A SEPARATE MODULE, NOT A COUPLES BRANCH OF `witness.search`:
`witness.couples` is deliberately NOT registered in `witness.mechanisms`
(see that module's own docstring, "WHAT IS NOT REGISTERED IN
witness.mechanisms"): a `CouplesProfile` is not a `witness.core.Profile`,
`couples_deferred_acceptance` is not a `MechanismSpec.run`, and a couple's
"target" is not a `witness.core.Profile` report but a joint ROL of PAIRS.
Forcing this through the flat search's generic interface would mean
pretending a joint ranking is a flat one. This module calls
`couples_deferred_acceptance` directly instead, exactly as
`witness.couples` itself recommends.

TWO DISTINCT TARGET KINDS, BOTH SEARCHED, BOTH REQUIRED:

  1. A SINGLE applicant's misreport, in a market that also contains
     couples. The report space is identical in shape to the flat search's
     (`witness.search.misreport_space` is reused verbatim -- a single's
     report is still just an ordered subset of `market.schools`). What is
     NEW here is the OUTCOME being generated by `couples_deferred_acceptance`
     rather than plain `deferred_acceptance`: classical applicant-proposing
     DA is strategy-proof for singles when nobody submits a joint report
     (Dubins & Freedman / Roth 1982), but `witness.couples`'s own module
     docstring explicitly declines to claim that survives couples ("Expect
     singleton sufficiency to FAIL under couples -- a couple's report
     changes which seats their partner competes for, so round-1
     independence dissolves" -- REVIEWER.md, SEQUENCING AND OPEN ITEMS).
     Searching singles' misreports here is a direct test of whether that
     expected failure is REAL, not assumed.

  2. A COUPLE's own misreport: their joint ROL of pairs. This is the
     mechanism's documented soft spot (REVIEWER.md: "NRMP residency match
     (couples is the documented soft spot)"). The report space is every
     ordered subset of ALL ordered pairs `(r, r2)` for `r, r2` in
     `market.schools` -- reusing `witness.search.ordered_subsets` UNCHANGED
     (it is generic over any hashable sequence of items, and a pair is just
     as valid an "item" as a school id is). This space is `n_schools ** 2`
     items instead of `n_schools`, so it explodes far faster; `max_space`
     below is a REQUIRED, checked argument for exactly that reason -- see
     `couple_misreport_space`.

WHAT COUNTS AS A COMPARABLE FINDING: exactly like
`scripts/couples_sequencing.py`'s own Deliverable A discipline, a candidate
misreport is only ever compared against the truthful outcome when BOTH runs
reach `STATUS_STABLE`. Comparing a real matching against a
`STATUS_LOOP_DETECTED` run's partial, heuristic-abandoned state would not be
a measurement of manipulability -- it would be a measurement of the loop
detector, which is explicitly out of scope here (see `witness.couples`'s own
honesty notes on what that status does and does not prove).

RULES INHERITED FROM `witness.search`'s OWN DISCIPLINE (unchanged in spirit):

  1. Improvement is judged ONLY by the target's TRUTHFUL report/joint
     ranking, never the false one. Strict preference only.
  2. Only the target's own report changes between the truthful and
     misreport profile -- every OTHER single's report and every OTHER
     couple's joint ROL is asserted byte-identical.
  3. The truthful run is computed once per instance and reused, and
     recomputed a second time solely to assert `couples_deferred_acceptance`
     is deterministic (mirrors `witness.search._truthful_run_with_
     determinism_check`).
  4. Enumeration order is canonical and deterministic (`ordered_subsets`'s
     own order), so a search returns the SAME witness on every run.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Mapping, Optional, Sequence

from witness.core import Market, WORST, content_hash
from witness.couples import (
    Couple,
    CouplesConfig,
    CouplesProfile,
    STATUS_STABLE,
    couples_deferred_acceptance,
)
from witness.da import Assignment
from witness.depth import ReportDepth, report_depth
from witness.errors import ModelError
from witness.search import ordered_subsets

#: Separate, smaller default from `witness.search.DEFAULT_MAX_SPACE` --
#: couple report space is `n_schools ** 2` items, not `n_schools`, so the
#: same numeric cap is reached at a much smaller `n_schools` (9 schools ->
#: 81 pair-items -> already far beyond any exhaustive budget). Callers that
#: know their `n_schools` is small enough may raise this explicitly.
DEFAULT_MAX_SPACE_COUPLE = 200_000

TARGET_SINGLE = "single"
TARGET_COUPLE = "couple"


def _pair_position(joint_rankings: Sequence[tuple], pair: tuple) -> float:
    """`pair`'s index in `joint_rankings`, or `WORST` if absent -- the exact
    convention `witness.oracles_couples._pair_position` uses, re-derived
    here independently (not imported) so this search module's notion of
    "the couple's truthful preference" shares no code with the oracle that
    will later be used to sanity-check any witness this module produces."""
    try:
        return float(tuple(joint_rankings).index(tuple(pair)))
    except ValueError:
        return WORST


def couple_strictly_prefers(joint_rankings: Sequence[tuple], a: tuple, b: tuple) -> bool:
    """True iff pair `a` is strictly preferred to pair `b` under
    `joint_rankings` -- the couples analogue of `witness.core.strictly_prefers`."""
    return _pair_position(joint_rankings, a) < _pair_position(joint_rankings, b)


def couple_misreport_space(
    market: Market,
    truthful_joint_rankings: Sequence[tuple],
    *,
    max_space: int = DEFAULT_MAX_SPACE_COUPLE,
) -> "tuple[tuple[tuple[str, str], ...], ...]":
    """Every legal joint ROL of pairs a couple could submit instead of
    `truthful_joint_rankings`: every ordered subset of ALL `n_schools ** 2`
    ordered pairs `(r, r2)`. Raises `ValueError` before enumerating if that
    would exceed `max_space` -- mirrors `witness.search.misreport_space`
    exactly, just over a squared item set."""
    schools = market.schools
    all_pairs = tuple((r, r2) for r in schools for r2 in schools)
    n = len(all_pairs)
    total = sum(math.perm(n, k) for k in range(n + 1))
    if total > max_space:
        raise ValueError(
            f"couple_misreport_space: {total} ordered subsets of {n} = "
            f"{len(schools)}**2 program-pairs exceeds max_space={max_space}"
        )
    truthful = tuple(tuple(p) for p in truthful_joint_rankings)
    return tuple(r for r in ordered_subsets(all_pairs) if r != truthful)


@dataclass(frozen=True)
class CoupleSearchWitness:
    """A single confirmed manipulation against `couples_deferred_acceptance`,
    for either target kind. Every field is a plain JSON-able type -- the
    schema `witness.replay_couples.verify_witness` reads independently."""

    witness_version: int
    mechanism: str
    config: Mapping
    market: Mapping
    truthful_profile: Mapping
    target_kind: str
    target_ids: tuple[str, ...]
    truthful_report: object
    false_report: object
    truthful_assignment: Mapping
    false_assignment: Mapping
    truthful_outcome: object
    false_outcome: object
    truthful_outcome_rank: Optional[int]
    false_outcome_rank: Optional[int]
    preference_proof: str
    depth: Optional[ReportDepth]
    witness_id: str

    def to_dict(self) -> dict:
        return {
            "witness_version": self.witness_version,
            "mechanism": self.mechanism,
            "config": dict(self.config),
            "market": dict(self.market),
            "truthful_profile": dict(self.truthful_profile),
            "target_kind": self.target_kind,
            "target_ids": list(self.target_ids),
            "truthful_report": self.truthful_report,
            "false_report": self.false_report,
            "truthful_assignment": dict(self.truthful_assignment),
            "false_assignment": dict(self.false_assignment),
            "truthful_outcome": self.truthful_outcome,
            "false_outcome": self.false_outcome,
            "truthful_outcome_rank": self.truthful_outcome_rank,
            "false_outcome_rank": self.false_outcome_rank,
            "preference_proof": self.preference_proof,
            "depth": self.depth.to_dict() if self.depth is not None else None,
            "witness_id": self.witness_id,
        }

    @staticmethod
    def from_dict(d: Mapping) -> "CoupleSearchWitness":
        return CoupleSearchWitness(
            witness_version=d["witness_version"],
            mechanism=d["mechanism"],
            config=dict(d["config"]),
            market=dict(d["market"]),
            truthful_profile=dict(d["truthful_profile"]),
            target_kind=d["target_kind"],
            target_ids=tuple(d["target_ids"]),
            truthful_report=d["truthful_report"],
            false_report=d["false_report"],
            truthful_assignment=dict(d["truthful_assignment"]),
            false_assignment=dict(d["false_assignment"]),
            truthful_outcome=d["truthful_outcome"],
            false_outcome=d["false_outcome"],
            truthful_outcome_rank=d["truthful_outcome_rank"],
            false_outcome_rank=d["false_outcome_rank"],
            preference_proof=d["preference_proof"],
            depth=ReportDepth.from_dict(d["depth"]) if d.get("depth") is not None else None,
            witness_id=d["witness_id"],
        )


def _with_single_report(
    profile: CouplesProfile, student: str, new_report: tuple[str, ...]
) -> CouplesProfile:
    singles = dict(profile.singles)
    singles[student] = tuple(new_report)
    return CouplesProfile(singles=singles, couples=profile.couples)


def _with_couple_report(
    profile: CouplesProfile, couple_index: int, new_joint_rankings: tuple[tuple[str, str], ...]
) -> CouplesProfile:
    couples = list(profile.couples)
    old = couples[couple_index]
    couples[couple_index] = Couple(members=old.members, joint_rankings=new_joint_rankings)
    return CouplesProfile(singles=profile.singles, couples=tuple(couples))


def _assert_only_target_changed(
    truthful: CouplesProfile, misreport: CouplesProfile, target_kind: str, target_ids: tuple[str, ...]
) -> None:
    """Rule 2: every OTHER participant's report is byte-identical."""
    for s, report in truthful.singles.items():
        if target_kind == TARGET_SINGLE and s == target_ids[0]:
            continue
        assert misreport.singles.get(s) == report, (
            f"misreport for {target_ids!r} perturbed single {s!r}'s report"
        )
    for i, c in enumerate(truthful.couples):
        if target_kind == TARGET_COUPLE and set(c.members) == set(target_ids):
            continue
        assert misreport.couples[i].joint_rankings == c.joint_rankings, (
            f"misreport for {target_ids!r} perturbed couple {c.members!r}'s joint ROL"
        )


def _run_twice_and_check_determinism(
    market: Market, profile: CouplesProfile, config: CouplesConfig
):
    first = couples_deferred_acceptance(market, profile, config)
    second = couples_deferred_acceptance(market, profile, config)
    if first.status != second.status or first.assignment != second.assignment:
        raise ModelError(
            "couples_deferred_acceptance is not deterministic: two runs on the "
            f"identical truthful (market, profile, config) produced "
            f"({first.status!r}, {first.assignment.to_dict()!r}) vs "
            f"({second.status!r}, {second.assignment.to_dict()!r})"
        )
    return first


def _build_single_witness(
    *, market, truthful_profile, target, config, truthful_report, false_report,
    truthful_assignment, false_assignment,
) -> CoupleSearchWitness:
    from witness.core import position as core_position

    truthful_outcome = truthful_assignment.of(target)
    false_outcome = false_assignment.of(target)
    truthful_rank = core_position(truthful_report, truthful_outcome)
    false_rank = core_position(truthful_report, false_outcome)
    proof = (
        f"single {target}'s truthful report is {list(truthful_report)!r}: under couples_da, "
        f"the truthful-report outcome {truthful_outcome!r} sits at rank "
        f"{'WORST' if truthful_rank == WORST else int(truthful_rank)}, while the "
        f"false-report outcome {false_outcome!r} sits at rank "
        f"{'WORST' if false_rank == WORST else int(false_rank)} -- strictly preferred."
    )
    depth = report_depth(truthful_report, false_report)
    base = {
        "witness_version": 1,
        "mechanism": config.mechanism,
        "config": config.to_dict(),
        "market": market.to_dict(),
        "truthful_profile": truthful_profile.to_dict(),
        "target_kind": TARGET_SINGLE,
        "target_ids": [target],
        "truthful_report": list(truthful_report),
        "false_report": list(false_report),
        "truthful_assignment": truthful_assignment.to_dict(),
        "false_assignment": false_assignment.to_dict(),
        "truthful_outcome": truthful_outcome,
        "false_outcome": false_outcome,
        "truthful_outcome_rank": None if truthful_rank == WORST else int(truthful_rank),
        "false_outcome_rank": None if false_rank == WORST else int(false_rank),
        "preference_proof": proof,
        "depth": depth.to_dict(),
    }
    witness_id = content_hash(base)
    full = dict(base)
    full["witness_id"] = witness_id
    return CoupleSearchWitness.from_dict(full)


def _build_couple_witness(
    *, market, truthful_profile, members, config, truthful_joint, false_joint,
    truthful_assignment, false_assignment,
) -> CoupleSearchWitness:
    a1, a2 = members
    truthful_pair = (truthful_assignment.of(a1), truthful_assignment.of(a2))
    false_pair = (false_assignment.of(a1), false_assignment.of(a2))
    truthful_rank = _pair_position(truthful_joint, truthful_pair)
    false_rank = _pair_position(truthful_joint, false_pair)
    proof = (
        f"couple {members!r}'s truthful joint ROL is {list(truthful_joint)!r}: under "
        f"couples_da, the truthful-report pair {truthful_pair!r} sits at rank "
        f"{'WORST' if truthful_rank == WORST else int(truthful_rank)}, while the "
        f"false-report pair {false_pair!r} sits at rank "
        f"{'WORST' if false_rank == WORST else int(false_rank)} -- strictly preferred "
        f"by the couple's own truthful joint ranking."
    )
    depth = None  # `witness.depth.report_depth` assumes a flat school-list report; not
    # meaningful for a joint ROL of pairs, so left unset rather than misapplied.
    base = {
        "witness_version": 1,
        "mechanism": config.mechanism,
        "config": config.to_dict(),
        "market": market.to_dict(),
        "truthful_profile": truthful_profile.to_dict(),
        "target_kind": TARGET_COUPLE,
        "target_ids": list(members),
        "truthful_report": [list(p) for p in truthful_joint],
        "false_report": [list(p) for p in false_joint],
        "truthful_assignment": truthful_assignment.to_dict(),
        "false_assignment": false_assignment.to_dict(),
        "truthful_outcome": list(truthful_pair),
        "false_outcome": list(false_pair),
        "truthful_outcome_rank": None if truthful_rank == WORST else int(truthful_rank),
        "false_outcome_rank": None if false_rank == WORST else int(false_rank),
        "preference_proof": proof,
        "depth": None,
    }
    witness_id = content_hash(base)
    full = dict(base)
    full["witness_id"] = witness_id
    return CoupleSearchWitness.from_dict(full)


def find_single_manipulation(
    market: Market,
    truthful_profile: CouplesProfile,
    target: str,
    config: CouplesConfig,
    *,
    max_space: int = 200_000,
) -> Optional[CoupleSearchWitness]:
    """The first profitable misreport for single applicant `target` (who is
    NOT part of a couple) in a market that may contain couples, in canonical
    enumeration order, or `None`."""
    from witness.search import misreport_space as flat_misreport_space
    from witness.core import strictly_prefers

    truthful_profile.validate_against(market)
    truthful_report = truthful_profile.singles[target]

    truthful_result = _run_twice_and_check_determinism(market, truthful_profile, config)
    if truthful_result.status != STATUS_STABLE:
        return None  # not a comparable baseline -- see module docstring
    truthful_assignment = truthful_result.assignment
    truthful_outcome = truthful_assignment.of(target)

    for false_report in flat_misreport_space(market, target, truthful_report, max_space=max_space):
        misreport_profile = _with_single_report(truthful_profile, target, false_report)
        _assert_only_target_changed(truthful_profile, misreport_profile, TARGET_SINGLE, (target,))

        false_result = couples_deferred_acceptance(market, misreport_profile, config)
        if false_result.status != STATUS_STABLE:
            continue  # not a comparable outcome -- see module docstring
        false_assignment = false_result.assignment
        false_outcome = false_assignment.of(target)

        if strictly_prefers(truthful_report, false_outcome, truthful_outcome):
            return _build_single_witness(
                market=market,
                truthful_profile=truthful_profile,
                target=target,
                config=config,
                truthful_report=truthful_report,
                false_report=false_report,
                truthful_assignment=truthful_assignment,
                false_assignment=false_assignment,
            )
    return None


def find_couple_manipulation(
    market: Market,
    truthful_profile: CouplesProfile,
    couple_index: int,
    config: CouplesConfig,
    *,
    max_space: int = DEFAULT_MAX_SPACE_COUPLE,
) -> Optional[CoupleSearchWitness]:
    """The first profitable joint-ROL misreport for
    `truthful_profile.couples[couple_index]`, in canonical enumeration
    order, or `None`."""
    truthful_profile.validate_against(market)
    couple = truthful_profile.couples[couple_index]
    members = couple.members
    truthful_joint = couple.joint_rankings

    truthful_result = _run_twice_and_check_determinism(market, truthful_profile, config)
    if truthful_result.status != STATUS_STABLE:
        return None
    truthful_assignment = truthful_result.assignment

    for false_joint in couple_misreport_space(market, truthful_joint, max_space=max_space):
        misreport_profile = _with_couple_report(truthful_profile, couple_index, false_joint)
        _assert_only_target_changed(truthful_profile, misreport_profile, TARGET_COUPLE, members)

        false_result = couples_deferred_acceptance(market, misreport_profile, config)
        if false_result.status != STATUS_STABLE:
            continue
        false_assignment = false_result.assignment

        truthful_pair = (truthful_assignment.of(members[0]), truthful_assignment.of(members[1]))
        false_pair = (false_assignment.of(members[0]), false_assignment.of(members[1]))
        if couple_strictly_prefers(truthful_joint, false_pair, truthful_pair):
            return _build_couple_witness(
                market=market,
                truthful_profile=truthful_profile,
                members=members,
                config=config,
                truthful_joint=truthful_joint,
                false_joint=false_joint,
                truthful_assignment=truthful_assignment,
                false_assignment=false_assignment,
            )
    return None


def search_all(
    market: Market,
    truthful_profile: CouplesProfile,
    config: CouplesConfig,
    *,
    single_max_space: int = 200_000,
    couple_max_space: int = DEFAULT_MAX_SPACE_COUPLE,
) -> "tuple[CoupleSearchWitness, ...]":
    """The first manipulation per target (every single not in a couple, then
    every couple, in their declared order), reusing `witness.mechanisms`'
    stop-at-first-per-target discipline from `witness.search.search_all_students`."""
    truthful_profile.validate_against(market)
    witnesses: list[CoupleSearchWitness] = []
    for s in truthful_profile.singles:
        w = find_single_manipulation(market, truthful_profile, s, config, max_space=single_max_space)
        if w is not None:
            witnesses.append(w)
    for i in range(len(truthful_profile.couples)):
        w = find_couple_manipulation(market, truthful_profile, i, config, max_space=couple_max_space)
        if w is not None:
            witnesses.append(w)
    return tuple(witnesses)
